### ISSUE TITLE
Warnings during PEcAn tests/testpfts.R

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#431] opened 2015-04-24 15:03 UTC
When running [tests/testpfts.R](https://github.com/PecanProject/pecan/blob/master/tests/testpfts.R):

Most of these look benign but I wanted to report these just in case.  Some are plotting issues ( I think) but others look like NaN and other potential problems:

```
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
2: In sqrt(diag(vc)) : NaNs produced
3: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
4: In densfun(x, parm[1], parm[2], ...) : NaNs produced
5: In densfun(x, parm[1], parm[2], ...) : NaNs produced
6: In densfun(x, parm[1], parm[2], ...) : NaNs produced
7: In densfun(x, parm[1], parm[2], ...) : NaNs produced
8: In densfun(x, parm[1], parm[2], ...) : NaNs produced
9: In densfun(x, parm[1], parm[2], ...) : NaNs produced
10: In densfun(x, parm[1], parm[2], ...) : NaNs produced
11: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
12: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
13: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
14: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
15: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
16: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
17: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
18: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
19: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
20: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
21: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
22: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
23: In dgamma(c(0.0200141498955474, 0.0201209677045705, 0.0202277855135937,  ... :
  NaNs produced
24: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
25: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
26: In densfun(x, parm[1], parm[2], ...) : NaNs produced
27: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
28: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
29: In dgamma(c(0.0496, 0.0505417417417417, 0.0514834834834835,  ... : NaNs produced
30: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
31: In dgamma(c(0.0317553241799664, 0.0317899252266684, 0.0318245262733705,  ... :
  NaNs produced
32: In densfun(x, parm[1], parm[2], ...) : NaNs produced
33: In densfun(x, parm[1], parm[2], ...) : NaNs produced
34: In densfun(x, parm[1], parm[2], ...) : NaNs produced
35: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
36: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
37: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
38: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
39: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
40: In dweibull(c(548.006371312583, 583.581846860551, 619.157322408518,  ... :
  NaNs produced
41: In dgamma(c(0.0444304226856337, 0.044458512887086, 0.0444866030885383,  ... :
  NaNs produced
42: In dgamma(c(0.0317553241799664, 0.0317899252266684, 0.0318245262733705,  ... :
  NaNs produced
43: In dgamma(c(0.0317553241799664, 0.0317899252266684, 0.0318245262733705,  ... :
  NaNs produced
44: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
45: In dgamma(c(0.0317553241799664, 0.0317899252266684, 0.0318245262733705,  ... :
  NaNs produced
46: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
47: In dgamma(c(0.305499015053085, 0.310180084054703, 0.31486115305632,  ... :
  NaNs produced
48: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
49: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
50: In rug(trait.data[[trait]]$Y, lwd = 2, col = "purple") :
  some values will be clipped
```

**Comment by dlebauer** [comment] 2015-04-24 15:09
We haven't generally paid much attention to warnings in our packages (perhaps we should) but for tests in particular - the problem isn't so much the warning as if there are problems that the test is supposed to catch that aren't throwing an error.

@robkooper It would be good to have some comments in the header that explain the purpose / application of these tests. Also, would it be more appropriate to put them in the PEcAn.DB package? Either as a test or as a Rmd example (e.g. if the goal is to produce plots to evaluate the pfts and priors?) Or is this something that should be implemented within the BETYdb app itself?

**Comment by serbinsh** [comment] 2015-12-14 22:43
@dlebauer @robkooper This has been open awhile, we should probably come up with a plan to update tests and then close this.  Or keep it open but change the discussion

**Comment by robkooper** [comment] 2015-12-15 00:05
Closing, can reopen if this is causes other problems.

**Closed by robkooper** 2015-12-15 00:05 UTC
Labels: Discussion, Question
