### ISSUE TITLE
Resolving db.exists in Utils.R

### ISSUE THREAD

**Issue by apourmok** [PecanProject/pecan#206] opened 2014-09-11 13:49 UTC
We need a new way to check the existence of a database since right now we comment it out in Utils.R in order to make the fia2ED.R working.

**Comment by zhangwenx** [comment] 2015-02-02 22:13
created a pull request https://github.com/PecanProject/pecan/pull/360

**Comment by dlebauer** [comment] 2015-02-06 03:30
#360 looks okay, but it is hard to assess the problem it is addressing.

@apourmok It's not clear what the problem is - though it seems that there is perhaps some functionality to be added to db.exists. What is the functionality?

More importantly, it seems that there is an issue with fia2ed.r. What is the issue?

Please see https://github.com/PecanProject/pecan/wiki/ Github-issues for how to write a good bug report.

**Comment by apourmok** [comment] 2015-02-06 03:49
That problem is resolved. There is no issue with fia2ed.r The part that I working on now is speeding up the query since it takes 7-8 minutes for single extraction. I am using "explain analyze" to find out the bottleneck and as soon as I resolve it, I will push it to main line.

**Comment by dlebauer** [comment] 2015-02-06 03:58
how was the problem resolved? Can this issue be closed?

How is this related to #360? I don't see the connection with changes to
db.exists?

On Thursday, February 5, 2015, Afshin Pourmokhtarian <
notifications@github.com

**Comment by robkooper** [comment] 2015-02-06 04:27
This solves the problem where the code in db.exists was commented out (using a if (FALSE)) statement that would check to see if the user has read or write permission to the database.

Initially the code would check to see if the user table could be written with  a dummy record, this would only work for the bety database, but not for the FIA database, which is the problem @apourmok had. He solved it by disabling the write check. @zhangwenx  has implemented a nice way to see if the database user has write permission on the database without actually needing to write.

**Comment by dlebauer** [comment] 2015-02-06 06:54
Thanks Rob - sounds like these can be merged / closed

**Closed** 2015-02-06 10:43 UTC
