### ISSUE TITLE
question about dbfile.input.insert/ met.process

### ISSUE THREAD

**Issue by yan130** [PecanProject/pecan#1026] opened 2016-09-26 21:07 UTC
Hi,

I am using met.process to get some data & I want to insert into PostgreSQL DB some my existing data.

I met this issue when I execute met.process twice with the same site but with different years:

+ for dbfiles(DB TABLE), "unique_filename_and_path_per_machine" UNIQUE CONSTRAINT, btree (file_name, file_path, machine_id) 
+ the data for the same site for different time period will be store in the same directory --> file_path is the same.
+ filename doesn't contain year or time info --> file_name is the same

Therefore, the later execution will only have new entry in inputs(DB TABLE) but no corresponding entry in dbfiles(DB TABLE). and failed before gapfilling. 

I am not sure if I am understanding something wrong and cause this problem.

**Comment by mdietze** [comment] 2016-09-26 21:18
This is a duplicate of a known bug, #773, and one of our top priorities for the next release. Open pull requests aim to address this, I just haven't had a chance to review and reconcile them. Should be working soon.

**Comment by yan130** [comment] 2016-09-26 21:18
Thanks, @mdietze

**Closed by mdietze** 2016-09-26 21:18 UTC
